# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uQ9WJ2TVJ3vTQf5mqhQKRFlxfHvzQb8v
"""

print("hello")

print("hello \nworld ")
print("hey", end="--")

print("hello","hey")

age=10
print(age)
print( type(age))
city =jaipur
print(type(city))

city =jaipur
print( type (city))

city=jaipur
print(type(city))





city ="jaipur"
print(type(city))

company="regex"
year=2021
print(f"company name is {company} year is {year}")

username="aman"
msg= f"hello user {username}"

print(msg)
username "tushar"
print(msg)

username="aman"
msg= f"hello user {username}"

print(msg)
username= "tushar"
print(msg)